In [2]:
import numpy as np

In [3]:
lis=[1,2,3,4,5]
a=np.array(lis)
print(a)
a.dtype

[1 2 3 4 5]


dtype('int32')

In [4]:
b=np.asarray(lis)
print(b)

[1 2 3 4 5]


In [5]:
c=np.ones((3,6))
print(c)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [6]:
d=np.arange(18).reshape(3,6)
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [7]:
f=np.ones_like(d)
print(f)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [8]:
g=np.full([3,3,3],[3,4,6])
print(g)

[[[3 4 6]
  [3 4 6]
  [3 4 6]]

 [[3 4 6]
  [3 4 6]
  [3 4 6]]

 [[3 4 6]
  [3 4 6]
  [3 4 6]]]


In [9]:
h=np.full_like(d,[3,4,5,6,7,8])
print(h)

[[3 4 5 6 7 8]
 [3 4 5 6 7 8]
 [3 4 5 6 7 8]]


In [10]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
i=np.random.randn(7,3)
print(i)

[[-0.68881753  1.28127084  0.24403623]
 [ 1.79107024 -0.14447242 -0.97558232]
 [-0.16010692 -0.25357061  0.34206826]
 [-0.4538778   0.29127573 -1.06863452]
 [ 0.99815367 -1.46131034 -0.45407981]
 [-1.26569104 -1.15613351  0.46966772]
 [ 0.74799634 -0.52896483  0.12202957]]


In [11]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [12]:
i[names == 'Bob']

array([[-0.68881753,  1.28127084,  0.24403623],
       [-0.4538778 ,  0.29127573, -1.06863452]])

In [13]:
f=np.arange(18).reshape(2,3,3)
print(f)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [14]:
f.T

array([[[ 0,  9],
        [ 3, 12],
        [ 6, 15]],

       [[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]]])

In [15]:
f.transpose((2,0,1))

array([[[ 0,  3,  6],
        [ 9, 12, 15]],

       [[ 1,  4,  7],
        [10, 13, 16]],

       [[ 2,  5,  8],
        [11, 14, 17]]])

In [16]:
j=np.arange(12).reshape(4,3)
k=np.abs(j)
print(k)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
l=np.sqrt(j)
print(l)

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479]]


In [18]:
m=np.exp(l)
print(m)

[[ 1.          2.71828183  4.11325038]
 [ 5.65223367  7.3890561   9.35646902]
 [11.58243519 14.09403011 16.91882868]
 [20.08553692 23.62434292 27.56714845]]


In [89]:
np.ceil(p)


array([[ 4.,  1.,  1.],
       [ 6.,  7., 99.],
       [ 5.,  0.,  7.]])

In [77]:
lis1=[4,1,1,5.5,6.4,99,4.9,0,7]
p=np.array(lis1).reshape(3,3)
p

array([[ 4. ,  1. ,  1. ],
       [ 5.5,  6.4, 99. ],
       [ 4.9,  0. ,  7. ]])

In [29]:
o=np.floor(p)
o

array([[4., 1., 1.],
       [5., 6., 9.],
       [4., 0., 7.]])

In [38]:
q=np.rint(p)
q

array([[ 4.,  1.,  1.],
       [ 6.,  6., 99.],
       [ 5.,  0.,  7.]])

In [40]:
r=np.modf(p)
r

(array([[0. , 0. , 0. ],
        [0.5, 0.4, 0. ],
        [0.9, 0. , 0. ]]), array([[ 4.,  1.,  1.],
        [ 5.,  6., 99.],
        [ 4.,  0.,  7.]]))

In [50]:
s=np.isnan(p)
s

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [53]:
t=np.isinf(p)
t

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [65]:
np.logical_not(p)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [78]:
u=np.power,p
u


(<ufunc 'power'>, array([[ 4. ,  1. ,  1. ],
        [ 5.5,  6.4, 99. ],
        [ 4.9,  0. ,  7. ]]))

In [82]:
v=np.mod(p,3)
v

array([[1. , 1. , 1. ],
       [2.5, 0.4, 0. ],
       [1.9, 0. , 1. ]])

In [90]:
w=np.argmin(p)
w

7

In [92]:
x=np.cumsum(p)
x

array([  4. ,   5. ,   6. ,  11.5,  17.9, 116.9, 121.8, 121.8, 128.8])

In [94]:
y=np.cumprod(p)
y

array([4.000000e+00, 4.000000e+00, 4.000000e+00, 2.200000e+01,
       1.408000e+02, 1.393920e+04, 6.830208e+04, 0.000000e+00,
       0.000000e+00])